Repository PHOENIXCONTACT/MORYX-Template, pull requests merged in 2023-09, with the labels that each got.

#14 Update/remove resources
  src/MyApplication.App/Controllers/MyFacadeController.cs
  src/MyApplication.App/Pages/Test.cshtml
  src/MyApplication.Resources/MyResource.cs
Labels: enhancement

#16 Remove MyResource as it's not used anymore
  src/MyApplication.Resources/SomeResource.cs
  src/Tests/MyApplication.Tests/SomeCellTest.cs
Labels: bug

#17 Update Default Port to match description
  src/MyApplication.App/Properties/launchSettings.json
Labels: bug, documentation

#18 Fix Configurations
  src/MyApplication.App/Config/Moryx.Products.Management.ModuleConfig.json
  src/MyApplication.App/MyApplication.App.csproj
Labels: bug
